network:
    descriptor_size: 128
    n_clusters: null
    use_vlad: False
    use_resnet: True
data:
    resize_ratio: 0.5
    pos_neg_map_train: "../pos_neg_maps/pletmisc_07.npy"
    pos_neg_map_val: "../pos_neg_maps/garage_07.npy"
    sonar_range: 30
    sonar_width: 120
    max_sonar_angle: 60
    min_sonar_similarity: 0.7
    cfar_algorithm: "GOCA"
    sonar_yaw_step: 3
    sonar_rho_step: 1

    augmentation:
        jittering: 0.0
        anchor_yaw_min: -60
        anchor_yaw_max: 60
    filter: 'plet_arcface'
    n_positives: 5
    n_negatives: 10
    test_width: 256
    test_height: 200
    train_width: 1536
train:
    batch_size: 12
    eval_ep: 5
    save_ep: 50
    learning_rate: 0.001
    weight_decay: 0.
    milestones: [20, 40, 60, 80, 100, 120, 160, 180, 200, 220]
    gamma: 0.5
    resume: True
    show_triplets: False
    margin: 0.3
    use_ratio: False
    use_arcface: False
eval:
    knn: 4
    scan_stride: 2
    batch_size: 16
    display: False
